export const DISCOVERIES = [
  "Listeners who log their album tend to stay in sessions 18% longer.",
  "The most popular session length on Listen is 35 minutes.",
  "Evening sessions (after 8pm) average 9 minutes longer than morning ones.",
  "Users with a 7-day streak are 3× more likely to reach 30 days.",
  "The top 10% of listeners average over 2 hours of focused listening per week.",
  "Sessions logged with gear notes score 0.4 stars higher on average.",
  "Most listeners find their sweet spot between 25 and 45 minutes.",
  "Planar magnetic headphone users average 6% longer sessions.",
  "The best sessions tend to happen in the first hour after work.",
  "Users who rate their sessions are 40% more consistent week over week.",
  "Your ears adapt to critical listening within the first 5 minutes of a session.",
  "The longest session ever logged on Listen was 4 hours, 12 minutes.",
  "Quiet hours listeners (midnight–4am) report the highest average ratings.",
  "Dedicated listeners (7+ day streaks) average 3.4 sessions per week.",
  "Listening in a dark room increases reported immersion by 22%.",
  "Sessions over 40 minutes are 2× more likely to be rated 5 stars.",
  "The average listener logs 2.8 different albums per week.",
  "Users who set up their gear first average 11 more minutes per session.",
  "Tuesday is the most popular listening day. Sunday is the longest.",
  "High-impedance headphone users tend to listen 14% longer on average.",
  "The 'sweet spot' volume for critical listening is typically 75–80 dB.",
  "Listeners who take notes remember albums 3× better a month later.",
  "Over 60% of sessions on Listen happen with noise-cancelling enabled.",
  "A consistent time of day triples the chance of a 14-day streak.",
  "The average 5-star session is 43 minutes long.",
];
